In [1]:
import tensorflow as tf

In [2]:
x_tf = tf.Variable(25, dtype=tf.int16)

In [3]:
x_tf.shape

TensorShape([])

In [4]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [9]:
tf_s = tf.add(x_tf , y_tf)
tf_s

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [81]:
tf_s.numpy()

TypeError: numpy() takes 1 positional argument but 2 were given

In [14]:
type(tf_s.numpy())

numpy.int16

In [15]:
tf_f = tf.Variable(25.0)

In [16]:
tf_f

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=25.0>

In [17]:
import numpy as np

In [34]:
x = np.array([[3,5,15,20]])

In [35]:
len(x)

1

In [36]:
x.shape

(1, 4)

In [37]:
type(x)

numpy.ndarray

In [43]:
x[0][3]

20

In [44]:
x_t = x.T

In [45]:
x_t

array([[ 3],
       [ 5],
       [15],
       [20]])

In [46]:
x_t.shape

(4, 1)

In [54]:
z = np.zeros([1,3])

In [56]:
z.shape

(1, 3)

In [58]:
tf_v = tf.Variable([3,5,15,25])
tf_v

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 3,  5, 15, 25])>

In [59]:
tf_v

TensorShape([4])

In [77]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [78]:
# Euclidean distance from the origin L2Norm
np.linalg.norm(x)

25.573423705088842

In [79]:
# L1Norm Excels the difference between zero and non-zero
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2])

32

In [80]:
# Squared L2Norm is computaional cheaper. It is simply xTx no when the distinguish of zero and non-zero is important
np.dot(x, x.T)

654

In [84]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

25

In [85]:
# LpNorm Generalized Norm
    # Real number and Greater or equal to one
    # L2 and L1 Norm used to regularize objective functions
    # (Regularization is a technique used for tuning the function by adding an additional penalty term in the error function. 
    # The additional term controls the excessively fluctuating function such that the coefficients don't take extreme values.  
    # Is the process of adding information in order to solve an ill-posed problem or to prevent overfitting. )